#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

echo "==================== PRE COMMIT ===================="
echo "Ceci est un script qui s'exécute avant chaque commit automatiquement"
echo "afin de vérifier si le code est conforme aux standards du code attendu."
echo "En cas de problème, contactez la personne en charge du projet."
echo "==================== PRE COMMIT ===================="

pnpm run check-all
if [ $? -ne 0 ]; then
    echo "Des erreurs ont été détectées. Souhaitez-vous exécuter 'pnpm run fix-all' pour tenter de les corriger automatiquement ? (y/n)"
    read -r response
    if [[ "$response" =~ ^[Yy]$ ]]; then
        pnpm run fix-all
    else
        echo "Corrigez manuellement les erreurs avant de commiter."
        exit 1
    fi
fi
